Add federated authenticator for user portal and apps
wso2-extensions/identity-cloud pull request #280
Opened 2017-05-05 04:08 UTC by madurangasiriwardena

2017-05-05 04:45 UTC, malithie commented
I don't think we need to replicate all code in the basic authenticator here. For example multi attribute login etc. We don't have such requirements now. Rather than complicating the code I think it's better to add them when such requirements come. WDYT?
Let's improve this to support present requirements we have rather than generalising.

2017-05-09 08:28 UTC, dinusha-dilrukshi requested changes

2017-05-09 08:28 UTC, dinusha-dilrukshi commented on components/org.wso2.carbon.identity.cloud.authenticator.federated/src/main/java/org/wso2/carbon/identity/cloud/authenticator/federated/internal/IdentityCloudAuthenticatorServiceComponent.java
> +        log.debug("Setting the Realm Service");
Check for isDebugenabled()

2017-05-09 08:28 UTC, dinusha-dilrukshi commented on components/org.wso2.carbon.identity.cloud.authenticator.federated/src/main/java/org/wso2/carbon/identity/cloud/authenticator/federated/internal/IdentityCloudAuthenticatorServiceComponent.java
> +                log.info("IdentityCloudFederatedAuthenticator bundle is activated");
Should be log.debug() not log.info()

2017-05-09 08:28 UTC, dinusha-dilrukshi commented on components/org.wso2.carbon.identity.cloud.authenticator.federated/src/main/java/org/wso2/carbon/identity/cloud/authenticator/federated/internal/IdentityCloudAuthenticatorServiceComponent.java
> +            log.info("IdentityCloudFederatedAuthenticator bundle is deactivated");
Should be log.debug()

2017-05-09 08:28 UTC, dinusha-dilrukshi commented on components/org.wso2.carbon.identity.cloud.authenticator.federated/src/main/java/org/wso2/carbon/identity/cloud/authenticator/federated/internal/IdentityCloudAuthenticatorServiceComponent.java
> +        log.debug("UnSetting the Realm Service");
Check for isDebugenabled()

2017-05-09 08:39 UTC, madurangasiriwardena commented
@malithie , we have created [1] track this improvement.

[1] https://wso2.org/jira/browse/IDNCLOUD-221

2017-05-12 04:10 UTC, dinusha-dilrukshi approved these changes

2017-05-12 04:10 UTC, merged