WSOTWOCLOUD-730- Fixing [Identity Cloud] Dynamically create the topli…
wso2-extensions/identity-cloud pull request #299
Opened 2017-06-09 15:21 UTC by dimuthud

…nk menu using a config file

2017-06-12 19:04 UTC, malithie commented on jaggeryapps/admin/templates/header.jag
> +headerConfig  = readFile("/conf/toplink_menu.json");
So every time header gets loaded we read the file. Can you check whether this is pattern followed in other cases also

2017-06-13 12:14 UTC, madurangasiriwardena requested changes

2017-06-13 12:14 UTC, madurangasiriwardena commented on jaggeryapps/admin/conf/toplink_menu.json
> +    "url": "https://cloudmgt.cloud.wso2.com/cloudmgt/site/pages/index.jag"
Do we need to add the wso2 production urls to this?
Ideally these should be applied from the puppet and these values should be kept in hieradata and changed according to the environment.

2017-06-13 12:14 UTC, madurangasiriwardena commented on jaggeryapps/admin/templates/header.jag
> +         if(attr == "Domain"){
formatting issue.

2017-06-13 12:14 UTC, madurangasiriwardena commented on jaggeryapps/admin/templates/header.jag
> +                        if(attr == "Domain"){
formatting issue.

2017-06-13 12:14 UTC, madurangasiriwardena commented on jaggeryapps/admin/templates/header.jag
> +                        if(dropDowns == "false"){
formatting issue.

2017-06-13 12:14 UTC, madurangasiriwardena commented on jaggeryapps/admin/templates/header.jag
> +                        }else{
formatting issue.

2017-06-14 08:49 UTC, dimuthud commented on jaggeryapps/admin/conf/toplink_menu.json
> +    "url": "https://cloudmgt.cloud.wso2.com/cloudmgt/site/pages/index.jag"
Url has been replace with "#"

2017-06-14 09:18 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +headerConfig  = readFile("/conf/toplink_menu.json");
Introduced a new method getJsonFromFile(..).

2017-06-14 09:26 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +         if(attr == "Domain"){
Fixed.

2017-06-14 09:31 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                        if(dropDowns == "false"){
Fixed

2017-06-14 09:31 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                        if(attr == "Domain"){
Fixed

2017-06-14 09:35 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                        }else{
Fixed.

2017-06-16 08:14 UTC, madurangasiriwardena approved these changes

2017-06-16 08:22 UTC, madurangasiriwardena commented on jaggeryapps/admin/templates/header.jag
> +            log.error("Error while reading file " + pathTofile + "\n" + e);
Can you check the exception handling logic here? Do we need to log and throw? If it is printed like this, will it print the stacktrace?

2017-06-16 09:41 UTC, merged