Fix IDNCLOUD-280: Make application type options more meaningful for the end user.
wso2-extensions/identity-cloud pull request #312
Opened 2017-06-28 15:49 UTC by omindu

2017-06-28 16:27 UTC, malithie commented
please get the text in html reviewed with docs team

2017-06-28 16:27 UTC, malithie requested changes

2017-06-28 16:27 UTC, malithie commented on jaggeryapps/admin/serviceproviders/editsp.jag
> +                      <li><a id="agenttype" href="#">Standards-Based Federation</a></li>
Should this be standards-based or standard-based ? Can you please verify with someone from doc team

2017-06-28 16:27 UTC, malithie commented on jaggeryapps/admin/serviceproviders/editsp.jag
> +            $("#app-type-desc-url").attr('href', 'https://docs.wso2.com/display/IdentityCloud/Configuring+Agent-based+SSO');
Better to move these documentation links to some conf file and refer from that here.  So if the documentation links got changed it's easy to locate them

2017-06-29 04:55 UTC, malithie approved these changes

2017-06-29 05:07 UTC, merged

2017-06-29 05:07 UTC, omindu commented on jaggeryapps/admin/serviceproviders/editsp.jag
> +                      <li><a id="agenttype" href="#">Standards-Based Federation</a></li>
standards-based is the correct word.