Introducing new Billing function to Identity-Cloud
wso2-extensions/identity-cloud pull request #314
Opened 2017-06-29 12:47 UTC by dimuthud

2017-06-29 13:01 UTC, danushkaf requested changes

2017-06-29 13:01 UTC, danushkaf commented on jaggeryapps/admin/templates/header.jag
> +    var cloudMgtIndexPage = cloudMgtUrl+ "site/pages/index.jag";
space missing before "+"

2017-06-29 13:01 UTC, danushkaf commented on jaggeryapps/admin/templates/header.jag
> +    var loginResult = post(billingLoginUrl,data, {}, 'json');
space needed before "data"

2017-06-29 13:01 UTC, danushkaf commented on jaggeryapps/admin/templates/header.jag
> +              accountContent="Account";
space needed before and after "="

2017-06-29 13:01 UTC, danushkaf commented on jaggeryapps/admin/templates/header.jag
> +              date=endDate;
space needed before and after "="

2017-06-29 13:01 UTC, danushkaf commented on jaggeryapps/admin/templates/header.jag
> +                  accountContent="Trial Expired";
space needed before and after "="

2017-06-29 13:01 UTC, danushkaf commented on jaggeryapps/admin/templates/header.jag
> +                     log.error('Error occurred while performing inform of first login'+e);
space needed before and after "+"

2017-06-29 13:01 UTC, danushkaf commented on jaggeryapps/admin/templates/header.jag
> +             accountContent = "Trial – "+ (trialPeriod)  +" days to upgrade";
space needed before and after "+"

2017-06-29 13:01 UTC, danushkaf commented on jaggeryapps/admin/templates/header.jag
> +                 log.info("Access denied for tenant: " +tenantDomain + " with a DISABLED subscription. Redirected to CloudMgt");
space needed before and after "+"

2017-06-29 13:01 UTC, danushkaf commented on jaggeryapps/admin/templates/header.jag
> +        log.error('Error occurred while performing logging operation to identity-cloud' +e);
space needed after "+"

2017-06-29 13:01 UTC, danushkaf commented on jaggeryapps/admin/templates/header.jag
> +                    var subscriptionInfo ="";
space needed after "="

2017-06-30 06:49 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +        var isPaidAccount = billingResult.data.data.isPaidAccount;
Done

2017-06-30 06:52 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +    if(loginResult.data = true){
Done

2017-06-30 06:54 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                log.info("Cloud not logged into the Identity-Cloud");
Done.

2017-06-30 06:59 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +log.info("accountContent " + accountContent);
Done

2017-06-30 07:00 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                    var subscriptionInfo ="";
Done.

2017-06-30 07:01 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +        log.error('Error occurred while performing logging operation to identity-cloud' +e);
Done.

2017-06-30 07:41 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                 log.info("Access denied for tenant: " +tenantDomain + " with a DISABLED subscription. Redirected to CloudMgt");
Done.

2017-06-30 07:41 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +             accountContent = "Trial – "+ (trialPeriod)  +" days to upgrade";
Done.

2017-06-30 07:44 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                     log.error('Error occurred while performing inform of first login'+e);
Done

2017-06-30 07:44 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                  accountContent="Trial Expired";
Done.

2017-06-30 07:52 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +              accountContent="Account";
Done

2017-06-30 07:53 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +              date=endDate;
Done.

2017-06-30 07:53 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +    var loginResult = post(billingLoginUrl,data, {}, 'json');
Done

2017-06-30 07:54 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +    var cloudMgtIndexPage = cloudMgtUrl+ "site/pages/index.jag";
Done

2017-06-30 07:54 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                  accountContent = "Trial - " + (noOfDays+1) + " days to upgrade";
Done.

2017-06-30 08:56 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +        var isPaidAccount = billingResult.data.data.isPaidAccount;
We can not look billingResult.data.data.isPaidAccount because it can be false.

2017-06-30 14:28 UTC, ayshsandu requested changes

2017-06-30 14:28 UTC, ayshsandu commented on jaggeryapps/admin/templates/header.jag
> + try{
check code formatting of the whole file

2017-06-30 14:28 UTC, ayshsandu commented on jaggeryapps/admin/templates/header.jag
> +                var endDate = billingResult.data.data.endDate;
unnecessary indent

2017-06-30 15:34 UTC, ayshsandu requested changes

2017-06-30 15:34 UTC, ayshsandu commented on jaggeryapps/admin/templates/header.jag
> +            log.error('Response mismatch error for billingResult response');
Make this log more descriptive.Include unable to load billing information for which user or which tenant"

2017-06-30 15:34 UTC, ayshsandu commented on jaggeryapps/admin/templates/header.jag
> +             log.info("Trial account activated for tenant: " + tenantDomain);
make this a debug log.

2017-06-30 15:34 UTC, ayshsandu commented on jaggeryapps/admin/templates/header.jag
> +                 log.info("Access denied for tenant: " +tenantDomain + " with a DISABLED subscription. Redirected to CloudMgt");
Format the code, 
change info log to debug log

2017-06-30 15:34 UTC, ayshsandu commented on jaggeryapps/admin/templates/header.jag
> +                log.info("Cloud Admin - " + cloudAdminUserName + " not logged into the Identity-Cloud");
change info log to debug log

2017-06-30 15:34 UTC, ayshsandu commented on jaggeryapps/admin/templates/header.jag
> +log.info("Tenant domain - " + tenantDomain +", isTrailExpired - " + isTrailExpired + " , isTrialAccount - " + isTrialAccount + " , subscription - " + subscription + " , accountContent - " + accountCo
change info log to debug log

2017-07-04 13:22 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> + try{
Reformatted.

2017-07-04 13:24 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                var endDate = billingResult.data.data.endDate;
Changed

2017-07-04 13:34 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +             log.info("Trial account activated for tenant: " + tenantDomain);
Done.

2017-07-04 14:11 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                log.info("Cloud Admin - " + cloudAdminUserName + " not logged into the Identity-Cloud");
Done.

2017-07-04 14:22 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +log.info("Tenant domain - " + tenantDomain +", isTrailExpired - " + isTrailExpired + " , isTrialAccount - " + isTrialAccount + " , subscription - " + subscription + " , accountContent - " + accountCo
Done.

2017-07-04 14:24 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +                 log.info("Access denied for tenant: " +tenantDomain + " with a DISABLED subscription. Redirected to CloudMgt");
Done.

2017-07-04 14:58 UTC, dimuthud commented on jaggeryapps/admin/templates/header.jag
> +            log.error('Response mismatch error for billingResult response');
Done.

2017-07-06 04:06 UTC, danushkaf approved these changes

2017-07-06 04:07 UTC, merged